# Generated by Django 6.0.6 on 2026-06-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_contactinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingMatrixConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_menu_rate', models.DecimalField(decimal_places=2, default=2500.0, help_text='Cost per head for Standard Native Tier', max_digits=10)),
                ('premium_menu_rate', models.DecimalField(decimal_places=2, default=4500.0, help_text='Cost per head for Premium Continental Buffet', max_digits=10)),
                ('executive_menu_rate', models.DecimalField(decimal_places=2, default=7500.0, help_text='Cost per head for Executive Imperial Banquet', max_digits=10)),
                ('canopy_base_rate', models.DecimalField(decimal_places=2, default=15000.0, help_text='Cost charged per chunk of 50 guests if checked', max_digits=10)),
            ],
            options={
                'verbose_name': 'Pricing Matrix Configuration',
                'verbose_name_plural': 'Pricing Matrix Configurations',
            },
        ),
    ]
