# Generated by Django 6.0.6 on 2026-06-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_pricingmatrixconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='For internal tracking reference.', max_length=150)),
                ('image', models.ImageField(help_text='Upload high-res banner photos.', upload_to='hero_carousel/')),
                ('alt_text', models.CharField(default='Dina Catering & Luxury Rentals Setup', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Set display hierarchy position sequence.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility without deleting.')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
