# Generated by Django 6.0.6 on 2026-06-18 22:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Upload high-res banner photos straight to Cloudinary.', max_length=255, verbose_name='image'),
        ),
    ]
